<?php

class model_showCard3 extends Model
{

    function __construct()
    {
        parent::__construct();
    }

    function getBasketReview()
    {
        return parent::getBasket(); // TODO: Change the autogenerated stub
    }

    function getPostPrice()
    {
        self::sessionInit();
        $addressInfo = self::sessionGet('addressInfo');
        $addressInfo = unserialize($addressInfo);
        $cityId = $addressInfo['city'];
        $result =  $this->calculatePostPrice($cityId);

        $postTypeId = self::sessionGet('postTypeId');
        if($postTypeId == 1){
            $postPrice = $result['postPricePishtaz'];
        }else{
            $postPrice = $result['postPriceSefareshi'];
        }

        return $postPrice;

    }

}