<?php

class model_showCard extends Model
{

    function __construct()
    {
        parent::__construct();
    }

    function getBasket()
    {
        return parent::getBasket(); // TODO: Change the autogenerated stub
    }

    function deleteBasket($data)
    {
        $basketId = $data['basketId'];
        $sql = "DELETE FROM tbl_basket WHERE id = ?";
        $this->doQuery($sql, [$basketId]);
    }

    function updateBasket($data = [])
    {
        $basketId = $data['basketId'];
        $number = $data['number'];

        $sql = "UPDATE tbl_basket SET number = ? WHERE id = ?";
        $values = [$number, $basketId];
        $this->doQuery($sql, $values);
    }


}